- name: Data Manipulation
  hosts: web-servers
  gather_facts: true
  vars:
   my_name: devops-expert
  tasks:
  - name: will wait till reachable
  hosts: all
  gather_facts: no # important
  tasks:
  - name: copying file with playbook
    copy:
      src: docker-compose.yml
      dest: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      mode: 0777
    become: yes
    become_user: root